/*
  Builds the jury presentation.

  Run with:  node presentation/build_deck.js

  The deck is generated by code rather than assembled by hand so that any
  correction can be made once, here, and the whole file rebuilt.
*/

const path = require("path");
const pptxgen = require("pptxgenjs");

const ASSETS = path.join(__dirname, "..", "docs", "assets");
const OUT = path.join(__dirname, "Chatbot_Long_Term_Memory_Jury1.pptx");

/* --------------------------------------------------------------- palette */
/* The colours come from the project itself. The application marks a current
   fact green and a replaced fact amber, and those two states are the heart of
   the work, so the deck uses the same language. Navy carries the weight. */
const NAVY = "1E2761";
const NAVY_SOFT = "2E3D7A";
const ICE = "EEF2FB";
const CARD = "F7F9FC";
const WHITE = "FFFFFF";
const INK = "1A1D23";
const MUTED = "5B6472";
const FAINT = "8B94A3";
const LINE = "DDE3ED";
const GREEN = "047857";
const GREEN_BG = "ECFDF5";
const AMBER = "B45309";
const AMBER_BG = "FFFBEB";

const HEAD = "Cambria";
const BODY = "Calibri";
const MONO = "Consolas";

const W = 13.333;
const H = 7.5;
const M = 0.62;

const pres = new pptxgen();
pres.layout = "LAYOUT_WIDE";
pres.author = "Group 03";
pres.title = "Chatbot with Long-Term Memory";

/* --------------------------------------------------------------- helpers */

// A light content slide with its heading already placed.
function contentSlide(title, kicker) {
  const s = pres.addSlide();
  s.background = { color: WHITE };

  if (kicker) {
    s.addText(kicker.toUpperCase(), {
      x: M, y: 0.42, w: 9, h: 0.26,
      fontFace: BODY, fontSize: 11.5, bold: true, color: FAINT,
      charSpacing: 1.4, isTextBox: true, margin: 0,
    });
  }

  s.addText(title, {
    x: M, y: kicker ? 0.7 : 0.52, w: W - M * 2, h: 0.68,
    fontFace: HEAD, fontSize: 32, bold: true, color: NAVY,
    isTextBox: true, margin: 0,
  });

  return s;
}

// A soft rounded panel used to group content.
function card(s, x, y, w, h, fill) {
  s.addShape(pres.ShapeType.roundRect, {
    x, y, w, h,
    rectRadius: 0.1,
    fill: { color: fill || CARD },
    line: { color: LINE, width: 0.75 },
  });
}

// A filled circle holding a short label, used to number steps.
function badge(s, x, y, label, fill, textColor) {
  const d = 0.42;
  s.addShape(pres.ShapeType.ellipse, {
    x, y, w: d, h: d,
    fill: { color: fill || NAVY },
    line: { color: fill || NAVY, width: 0 },
  });
  s.addText(label, {
    x, y, w: d, h: d,
    fontFace: BODY, fontSize: 12.5, bold: true,
    color: textColor || WHITE, align: "center", valign: "middle",
    isTextBox: true, margin: 0,
  });
}

// One large number with a caption under it.
function statTile(s, x, y, w, value, label, color) {
  card(s, x, y, w, 1.32, CARD);
  s.addText(String(value), {
    x, y: y + 0.16, w, h: 0.6,
    fontFace: HEAD, fontSize: 30, bold: true,
    color: color || NAVY, align: "center",
    isTextBox: true, margin: 0,
  });
  s.addText(label.toUpperCase(), {
    x, y: y + 0.82, w, h: 0.3,
    fontFace: BODY, fontSize: 10, color: MUTED,
    align: "center", charSpacing: 0.8,
    isTextBox: true, margin: 0,
  });
}

function body(s, text, opts) {
  s.addText(text, Object.assign({
    fontFace: BODY, fontSize: 14.5, color: INK,
    lineSpacing: 21, valign: "top", isTextBox: true, margin: 0,
  }, opts));
}

function bullets(s, items, opts) {
  const runs = items.map((t, i) => ({
    text: t,
    options: { bullet: { indent: 14 }, breakLine: i !== items.length - 1 },
  }));
  s.addText(runs, Object.assign({
    fontFace: BODY, fontSize: 14, color: INK,
    paraSpaceAfter: 9, valign: "top", isTextBox: true, margin: 0,
  }, opts));
}

function caption(s, text, x, y, w) {
  s.addText(text, {
    x, y, w, h: 0.3,
    fontFace: BODY, fontSize: 10.5, italic: true, color: FAINT,
    isTextBox: true, margin: 0,
  });
}

/* ================================================================== 1 */

{
  const s = pres.addSlide();
  s.background = { color: NAVY };

  s.addText("Chatbot with Long-Term Memory", {
    x: M + 0.15, y: 2.0, w: 11.2, h: 0.95,
    fontFace: HEAD, fontSize: 44, bold: true, color: WHITE,
    isTextBox: true, margin: 0,
  });

  s.addText("A memory layer that lets a language model remember a user between conversations", {
    x: M + 0.15, y: 3.02, w: 10.4, h: 0.5,
    fontFace: BODY, fontSize: 16, color: "C3CFEA",
    isTextBox: true, margin: 0,
  });

  s.addShape(pres.ShapeType.roundRect, {
    x: M + 0.15, y: 3.85, w: 4.35, h: 0.44,
    rectRadius: 0.22,
    fill: { color: NAVY_SOFT }, line: { color: "44559B", width: 0.75 },
  });
  s.addText("Topic 192   |   Model Making   |   Jury 1", {
    x: M + 0.15, y: 3.85, w: 4.35, h: 0.44,
    fontFace: BODY, fontSize: 12, color: "D6DEF5",
    align: "center", valign: "middle", isTextBox: true, margin: 0,
  });

  s.addText([
    { text: "Swaraj Mandre", options: { breakLine: true } },
    { text: "Memory design and retrieval", options: { breakLine: true, fontSize: 10.5, color: "9FB0D9" } },
    { text: "Saumya Joshi", options: { breakLine: true } },
    { text: "Language model integration", options: { breakLine: true, fontSize: 10.5, color: "9FB0D9" } },
    { text: "Siddhant Pawar", options: { breakLine: true } },
    { text: "Evaluation and interface", options: { fontSize: 10.5, color: "9FB0D9" } },
  ], {
    x: M + 0.15, y: 4.62, w: 4.5, h: 1.8,
    fontFace: BODY, fontSize: 13, color: WHITE,
    lineSpacing: 16, valign: "top", isTextBox: true, margin: 0,
  });

  s.addText([
    { text: "Guided by", options: { breakLine: true, fontSize: 11, color: "9FB0D9" } },
    { text: "Prof. Dr. Snehalata Funde", options: { breakLine: true, fontSize: 14 } },
    { text: "", options: { breakLine: true, fontSize: 6 } },
    { text: "MIT School of Computing", options: { breakLine: true, fontSize: 11.5, color: "9FB0D9" } },
    { text: "MIT Art, Design and Technology University", options: { fontSize: 11.5, color: "9FB0D9" } },
  ], {
    x: 5.6, y: 4.72, w: 5.2, h: 1.3,
    fontFace: BODY, color: WHITE, lineSpacing: 18,
    valign: "top",
    isTextBox: true, margin: 0,
  });

  s.addNotes("Introduce the topic and the team. Topic 192 is a Model Making topic, so the same project continues into Jury 2 and the end semester jury.");
}

/* ================================================================== 2 */

{
  const s = contentSlide("A language model forgets everything", "The problem");

  body(s,
    "A transformer answers using only the text placed inside its context window, and that window is a " +
    "fixed size. The model keeps no state of its own between calls. When a conversation ends, every " +
    "detail the user shared is gone.",
    { x: M, y: 1.62, w: 6.5, h: 1.3 });

  body(s,
    "The user is left repeating themselves. The assistant never builds up any picture of who it is " +
    "talking to, so it cannot give advice that depends on what it was told last week.",
    { x: M, y: 3.02, w: 6.5, h: 1.1 });

  card(s, M, 4.35, 6.5, 1.62, ICE);
  s.addText("What we were asked to build", {
    x: M + 0.28, y: 4.55, w: 5.9, h: 0.3,
    fontFace: BODY, fontSize: 11.5, bold: true, color: NAVY,
    charSpacing: 0.6, isTextBox: true, margin: 0,
  });
  s.addText(
    "A chatbot that stores past turns and facts in a memory store, retrieves the relevant ones, " +
    "and uses them to answer new questions across sessions.",
    {
      x: M + 0.28, y: 4.88, w: 5.94, h: 0.95,
      fontFace: BODY, fontSize: 13.5, color: INK, italic: true,
      lineSpacing: 19, valign: "top", isTextBox: true, margin: 0,
    });

  // Right side: the gap made visual.
  card(s, 7.5, 1.62, 5.22, 4.35, CARD);

  s.addText("Without a memory layer", {
    x: 7.78, y: 1.85, w: 4.6, h: 0.3,
    fontFace: BODY, fontSize: 12, bold: true, color: MUTED,
    isTextBox: true, margin: 0,
  });

  const convo = [
    ["Session 1", "I live in Pune and I study AI.", NAVY_SOFT, WHITE],
    ["Session 2", "Where do I live?", NAVY_SOFT, WHITE],
    ["Assistant", "I have no record of that.", AMBER_BG, AMBER],
  ];
  let cy = 2.3;
  convo.forEach(([who, line, bg, fg]) => {
    s.addText(who.toUpperCase(), {
      x: 7.78, y: cy, w: 2.0, h: 0.24,
      fontFace: BODY, fontSize: 9.5, bold: true, color: FAINT,
      charSpacing: 0.8, isTextBox: true, margin: 0,
    });
    s.addShape(pres.ShapeType.roundRect, {
      x: 7.78, y: cy + 0.26, w: 4.66, h: 0.62,
      rectRadius: 0.09,
      fill: { color: bg },
      line: { color: bg === AMBER_BG ? "F0CE96" : bg, width: 0.75 },
    });
    s.addText(line, {
      x: 7.94, y: cy + 0.26, w: 4.4, h: 0.62,
      fontFace: BODY, fontSize: 12.5, color: fg,
      valign: "middle", isTextBox: true, margin: 0,
    });
    cy += 1.06;
  });

  s.addText("The detail was never stored anywhere, so there is nothing to look up.", {
    x: 7.78, y: 5.55, w: 4.66, h: 0.34,
    fontFace: BODY, fontSize: 11, italic: true, color: MUTED,
    isTextBox: true, margin: 0,
  });

  s.addNotes("Make the point that this is an architectural limit of the transformer, not a bug. The context window is finite and the model is stateless between calls.");
}

/* ================================================================== 3 */

{
  const s = contentSlide("Where this problem already shows up", "Grounding and scope");

  body(s,
    "Shipped products and published research have both had to solve it.",
    { x: M, y: 1.6, w: 7.1, h: 0.34, fontSize: 14 });

  const examples = [
    ["ChatGPT Memory",
     "Carries user details between separate conversations instead of starting blank.",
     "OpenAI, February 2024"],
    ["MemGPT",
     "Moves information between a small context and a larger store, the way an operating system moves pages between memory and disk.",
     "Packer et al., arXiv:2310.08560, 2023"],
    ["Mem0",
     "An open source memory layer that keeps user facts between sessions.",
     "github.com/mem0ai/mem0"],
  ];

  let ey = 2.16;
  examples.forEach(([name, text, src], i) => {
    card(s, M, ey, 7.1, 1.32, CARD);
    badge(s, M + 0.26, ey + 0.24, String(i + 1), NAVY, WHITE);
    s.addText(name, {
      x: M + 0.8, y: ey + 0.18, w: 6.0, h: 0.3,
      fontFace: BODY, fontSize: 13.5, bold: true, color: NAVY,
      isTextBox: true, margin: 0,
    });
    s.addText(text, {
      x: M + 0.8, y: ey + 0.5, w: 6.05, h: 0.5,
      fontFace: BODY, fontSize: 11.5, color: MUTED,
      lineSpacing: 15, valign: "top", isTextBox: true, margin: 0,
    });
    s.addText(src, {
      x: M + 0.8, y: ey + 1.0, w: 6.05, h: 0.24,
      fontFace: BODY, fontSize: 9.5, italic: true, color: FAINT,
      valign: "top", isTextBox: true, margin: 0,
    });
    ey += 1.42;
  });

  card(s, 8.06, 1.6, 4.66, 4.36, ICE);
  s.addText("What our system had to do", {
    x: 8.34, y: 1.84, w: 4.1, h: 0.32,
    fontFace: BODY, fontSize: 13.5, bold: true, color: NAVY,
    isTextBox: true, margin: 0,
  });

  const jobs = [
    "Store the raw messages and the facts inside them",
    "Retrieve by meaning rather than by matching words",
    "Recall details after the program has been closed",
    "Replace a fact as soon as it is contradicted",
    "Strip personal details before anything is written",
  ];

  let jy = 2.34;
  jobs.forEach((t) => {
    s.addShape(pres.ShapeType.ellipse, {
      x: 8.36, y: jy + 0.13, w: 0.13, h: 0.13,
      fill: { color: GREEN }, line: { color: GREEN, width: 0 },
    });
    s.addText(t, {
      x: 8.66, y: jy, w: 3.82, h: 0.7,
      fontFace: BODY, fontSize: 12.5, color: INK,
      lineSpacing: 16, valign: "top", isTextBox: true, margin: 0,
    });
    jy += 0.70;
  });

  s.addNotes("Keep this short. Name the three systems, then read the five requirements down the right hand side.");
}

/* ================================================================== 4 */

{
  const s = contentSlide("How one message travels through the system", "Architecture");

  const stages = [
    ["User message", "Typed in the browser"],
    ["Fact extraction", "DeepSeek v4 Flash"],
    ["Memory store", "ChromaDB on disk"],
    ["Retrieval", "Cosine and recency"],
    ["Prompt assembly", "Memories in system text"],
    ["Reply", "DeepSeek v4 Flash"],
  ];

  const bw = 1.86, gap = 0.13;
  let x = M;
  const y = 2.05;

  stages.forEach(([name, sub], i) => {
    const isStore = i === 2;
    s.addShape(pres.ShapeType.roundRect, {
      x, y, w: bw, h: 1.5,
      rectRadius: 0.1,
      fill: { color: isStore ? NAVY : CARD },
      line: { color: isStore ? NAVY : LINE, width: 0.75 },
    });
    s.addText(name, {
      x: x + 0.1, y: y + 0.3, w: bw - 0.2, h: 0.42,
      fontFace: BODY, fontSize: 12.5, bold: true,
      color: isStore ? WHITE : NAVY, align: "center",
      isTextBox: true, margin: 0,
    });
    s.addText(sub, {
      x: x + 0.08, y: y + 0.76, w: bw - 0.16, h: 0.5,
      fontFace: BODY, fontSize: 10, color: isStore ? "BFCCEC" : MUTED,
      align: "center", lineSpacing: 13, valign: "top", isTextBox: true, margin: 0,
    });

    if (i < stages.length - 1) {
      s.addShape(pres.ShapeType.rightArrow, {
        x: x + bw + 0.005, y: y + 0.66, w: gap + 0.11, h: 0.18,
        fill: { color: FAINT }, line: { color: FAINT, width: 0 },
      });
    }
    x += bw + gap;
  });

  caption(s, "Every message follows the same six stages.", M, 3.68, 8);

  const notes = [
    ["Embeddings never leave this machine",
     "The model that turns text into numbers runs locally, so stored memories are never sent to an API. Only the current message and the few memories retrieved for it are sent."],
    ["The store is asked to filter, not just to search",
     "Replaced facts are excluded by the database during the search, so they are never candidates in the first place."],
    ["The database can be swapped",
     "ChromaDB sits behind a small interface, so moving to another vector database later means adding one file."],
  ];

  let ny = 4.18;
  notes.forEach(([h, t]) => {
    s.addShape(pres.ShapeType.ellipse, {
      x: M, y: ny + 0.08, w: 0.13, h: 0.13,
      fill: { color: NAVY }, line: { color: NAVY, width: 0 },
    });
    s.addText(h, {
      x: M + 0.3, y: ny, w: 11.4, h: 0.28,
      fontFace: BODY, fontSize: 13, bold: true, color: NAVY,
      isTextBox: true, margin: 0,
    });
    s.addText(t, {
      x: M + 0.3, y: ny + 0.3, w: 11.4, h: 0.42,
      fontFace: BODY, fontSize: 12, color: MUTED,
      lineSpacing: 16, valign: "top", isTextBox: true, margin: 0,
    });
    ny += 0.8;
  });

  s.addNotes("If asked why not FAISS: FAISS has no metadata filtering, so replaced facts could only be removed after the search, which silently shrinks the result set.");
}

/* ================================================================== 5 */

{
  const s = contentSlide("Three layers, each with a different job", "Memory design");

  const layers = [
    ["Working memory", "The last six messages, kept word for word.",
     "Lives in the running program only. Cleared when a new session starts, which is what proves later recall came from the database.", NAVY],
    ["Episodic memory", "The raw messages the user typed.",
     "Stored and searchable. Useful for questions about the conversation itself. Trimmed when the store grows too large.", NAVY_SOFT],
    ["Semantic memory", "Short facts such as city: Mumbai.",
     "Each fact is dated and versioned. A newer fact replaces an older one instead of sitting beside it. This is the layer that resolves contradictions.", GREEN],
  ];

  let x = M;
  const cw = 3.86;
  layers.forEach(([name, one, detail, accent], i) => {
    card(s, x, 1.78, cw, 3.5, CARD);
    badge(s, x + 0.28, 2.04, String(i + 1), accent, WHITE);
    s.addText(name, {
      x: x + 0.82, y: 2.02, w: cw - 1.1, h: 0.42,
      fontFace: HEAD, fontSize: 17, bold: true, color: accent,
      valign: "middle", isTextBox: true, margin: 0,
    });
    s.addText(one, {
      x: x + 0.28, y: 2.62, w: cw - 0.56, h: 0.6,
      fontFace: BODY, fontSize: 13, bold: true, color: INK,
      lineSpacing: 18, valign: "top", isTextBox: true, margin: 0,
    });
    s.addText(detail, {
      x: x + 0.28, y: 3.3, w: cw - 0.56, h: 1.7,
      fontFace: BODY, fontSize: 12, color: MUTED,
      lineSpacing: 17, valign: "top", isTextBox: true, margin: 0,
    });
    x += cw + 0.24;
  });

  card(s, M, 5.48, 11.9, 1.0, ICE);
  s.addText(
    "The split matters. Raw messages are bulky and repetitive, so they are capped and trimmed. " +
    "Facts are small and already condensed, so they are kept for good.",
    {
      x: M + 0.3, y: 5.68, w: 11.3, h: 0.62,
      fontFace: BODY, fontSize: 13, color: INK,
      lineSpacing: 18, valign: "top", isTextBox: true, margin: 0,
    });

  s.addNotes("Naming the three layers clearly is worth doing slowly. Most questions about the design start here.");
}

/* ================================================================== 6 */

{
  const s = contentSlide("Searching by meaning instead of by words", "Step 2, retrieval");

  body(s,
    "Every memory is turned into a list of 384 numbers by a model that runs on this machine. " +
    "Sentences with a similar meaning end up with similar numbers, so we can compare meaning by " +
    "measuring the angle between two lists.",
    { x: M, y: 1.62, w: 6.35, h: 1.2, fontSize: 14 });

  card(s, M, 2.98, 6.35, 1.62, ICE);
  s.addText("Measured on our own system", {
    x: M + 0.28, y: 3.14, w: 5.8, h: 0.28,
    fontFace: BODY, fontSize: 11, bold: true, color: NAVY,
    isTextBox: true, margin: 0,
  });
  s.addText([
    { text: "I live in Pune", options: { fontFace: MONO, fontSize: 11 } },
    { text: "  and  ", options: { fontSize: 11, color: MUTED } },
    { text: "My home city is Pune", options: { fontFace: MONO, fontSize: 11, breakLine: true } },
    { text: "score 0.821", options: { bold: true, color: GREEN, fontSize: 13, breakLine: true } },
    { text: "The same sentence against ", options: { fontSize: 11, color: MUTED } },
    { text: "I enjoy playing cricket", options: { fontFace: MONO, fontSize: 11, breakLine: true } },
    { text: "score 0.351", options: { bold: true, color: MUTED, fontSize: 13 } },
  ], {
    x: M + 0.28, y: 3.44, w: 5.8, h: 1.05,
    fontFace: BODY, color: INK, lineSpacing: 16,
    valign: "top",
    isTextBox: true, margin: 0,
  });

  body(s,
    "Similarity alone is not enough, because it has no sense of time. Two memories can match a " +
    "question equally well while one of them is months out of date. So the final score adds a small " +
    "bonus for being recent, and a small bonus for being a tidy fact rather than a raw sentence.",
    { x: M, y: 4.78, w: 6.35, h: 1.4, fontSize: 13.5 });

  s.addImage({
    path: path.join(ASSETS, "01a_retrieval_panel.png"),
    x: 7.34, y: 1.72, w: 5.38, h: 2.78,
  });
  caption(s, "Live from the running system. Every retrieved memory shows its similarity, its recency and the final score.",
    7.34, 4.58, 5.38);

  s.addNotes("This slide answers the first likely jury question, how do you retrieve the right memory.");
}

/* ================================================================== 7 */

{
  const s = contentSlide("Remembering after the program restarts", "Step 3, across sessions");

  body(s,
    "Chat history alone is not memory. To show the difference, the demo starts a new session, " +
    "which empties the list of recent messages completely.",
    { x: M, y: 1.62, w: 4.6, h: 1.0, fontSize: 14 });

  body(s,
    "From that point there is nothing in the running program to answer from. Anything the assistant " +
    "recalls has to come out of the database on disk.",
    { x: M, y: 2.72, w: 4.6, h: 1.0, fontSize: 14 });

  card(s, M, 3.86, 4.6, 2.0, GREEN_BG);
  s.addText("What the screenshot shows", {
    x: M + 0.26, y: 4.04, w: 4.1, h: 0.28,
    fontFace: BODY, fontSize: 11.5, bold: true, color: GREEN,
    isTextBox: true, margin: 0,
  });
  bullets(s, [
    "Working memory is empty",
    "The question is asked fresh",
    "The answer still names Pune",
  ], { x: M + 0.26, y: 4.36, w: 4.1, h: 1.34, fontSize: 12.5, color: INK });

  s.addImage({
    path: path.join(ASSETS, "02_cross_session_recall.png"),
    x: 5.6, y: 1.7, w: 7.12, h: 4.46,
  });
  caption(s, "Session 2, started with recent messages cleared.", 5.6, 6.24, 7.12);

  s.addNotes("Offer to close the program entirely and restart it. The memory survives because it is written to disk, not held in the process.");
}

/* ================================================================== 8 */

{
  const s = contentSlide("A newer fact retires the older one", "Step 4, conflicting facts");

  body(s,
    "When the user says something that contradicts a stored fact, the old record is not deleted and " +
    "the two are not kept as equals. The old one is marked as replaced and stays in the database as " +
    "history. Searches only look at current records, so the outdated value can never be returned again.",
    { x: M, y: 1.62, w: 6.2, h: 1.5, fontSize: 14 });

  // Before and after
  const rows = [
    ["Before", "city: Pune", "current", GREEN, GREEN_BG],
    ["After", "city: Pune", "replaced", AMBER, AMBER_BG],
    ["", "city: Mumbai", "current", GREEN, GREEN_BG],
  ];
  let ry = 3.3;
  rows.forEach(([label, text, state, color, bg]) => {
    if (label) {
      s.addText(label.toUpperCase(), {
        x: M, y: ry + 0.06, w: 0.85, h: 0.3,
        fontFace: BODY, fontSize: 10, bold: true, color: FAINT,
        charSpacing: 0.8, isTextBox: true, margin: 0,
      });
    }
    s.addShape(pres.ShapeType.roundRect, {
      x: M + 0.9, y: ry, w: 5.3, h: 0.52,
      rectRadius: 0.08,
      fill: { color: bg }, line: { color: color, width: 0.75 },
    });
    s.addText(text, {
      x: M + 1.06, y: ry, w: 3.1, h: 0.52,
      fontFace: MONO, fontSize: 12, color: INK,
      valign: "middle", isTextBox: true, margin: 0,
    });
    s.addText(state, {
      x: M + 4.2, y: ry, w: 1.85, h: 0.52,
      fontFace: BODY, fontSize: 11, bold: true, color: color,
      align: "right", valign: "middle", isTextBox: true, margin: 0,
    });
    ry += 0.66;
  });

  body(s,
    "Keeping the old record rather than overwriting it means the history of a fact can still be read " +
    "back, which matters if anyone ever needs to check why the assistant believes something.",
    { x: M, y: 5.44, w: 6.2, h: 0.9, fontSize: 13 });

  s.addImage({
    path: path.join(ASSETS, "03a_contradiction_panel.png"),
    x: 7.2, y: 2.05, w: 5.52, h: 1.33,
  });
  caption(s, "The panel names both records, so the change is auditable during the demo.", 7.2, 3.5, 5.52);

  s.addImage({
    path: path.join(ASSETS, "03c_statistics.png"),
    x: 7.2, y: 4.1, w: 5.52, h: 1.94,
  });
  caption(s, "Replaced facts are counted separately from current ones.", 7.2, 6.12, 5.52);

  s.addNotes("This answers the second likely jury question, how do you handle outdated or conflicting memories.");
}

/* ================================================================== 9 */

{
  const s = contentSlide("Why similarity on its own gets this wrong", "Evidence");

  body(s,
    "We tested this rather than assuming it. The same four questions were asked twice, once with " +
    "replaced facts filtered out and once with them left in.",
    { x: M, y: 1.6, w: 11.9, h: 0.6, fontSize: 14.5 });

  const head = ["Question asked", "Outdated fact returned", "Similarity score"];
  const data = [
    ["Which city am I living in?", "Pune", "0.424"],
    ["Who do I work for?", "Infosys", "0.416"],
    ["What sport do I like most?", "football", "0.651"],
    ["What do I eat?", "vegetarian", "0.381"],
  ];

  const colX = [M, M + 4.9, M + 8.3];
  const colW = [4.7, 3.2, 2.6];

  s.addShape(pres.ShapeType.roundRect, {
    x: M, y: 2.4, w: 11.9, h: 0.5, rectRadius: 0.07,
    fill: { color: NAVY }, line: { color: NAVY, width: 0 },
  });
  head.forEach((h, i) => {
    s.addText(h.toUpperCase(), {
      x: colX[i] + 0.22, y: 2.4, w: colW[i], h: 0.5,
      fontFace: BODY, fontSize: 10.5, bold: true, color: WHITE,
      charSpacing: 0.7, valign: "middle", isTextBox: true, margin: 0,
    });
  });

  let ty = 2.96;
  data.forEach((row) => {
    s.addShape(pres.ShapeType.roundRect, {
      x: M, y: ty, w: 11.9, h: 0.52, rectRadius: 0.06,
      fill: { color: CARD }, line: { color: LINE, width: 0.75 },
    });
    row.forEach((cell, i) => {
      s.addText(cell, {
        x: colX[i] + 0.22, y: ty, w: colW[i], h: 0.52,
        fontFace: i === 0 ? BODY : MONO,
        fontSize: i === 0 ? 13 : 12,
        bold: i === 2,
        color: i === 1 ? AMBER : INK,
        valign: "middle", isTextBox: true, margin: 0,
      });
    });
    ty += 0.6;
  });

  card(s, M, 5.5, 5.83, 1.28, AMBER_BG);
  s.addText("Filter switched off", {
    x: M + 0.28, y: 5.66, w: 5.2, h: 0.3,
    fontFace: BODY, fontSize: 12, bold: true, color: AMBER,
    isTextBox: true, margin: 0,
  });
  s.addText("4 of 4 questions were given an outdated fact as though it were true.", {
    x: M + 0.28, y: 5.96, w: 5.3, h: 0.62,
    fontFace: BODY, fontSize: 12.5, color: INK,
    lineSpacing: 16, valign: "top", isTextBox: true, margin: 0,
  });

  card(s, M + 6.07, 5.5, 5.83, 1.28, GREEN_BG);
  s.addText("Filter switched on", {
    x: M + 6.35, y: 5.66, w: 5.2, h: 0.3,
    fontFace: BODY, fontSize: 12, bold: true, color: GREEN,
    isTextBox: true, margin: 0,
  });
  s.addText("0 of 4. The correct current fact was returned every time.", {
    x: M + 6.35, y: 5.96, w: 5.3, h: 0.62,
    fontFace: BODY, fontSize: 12.5, color: INK,
    lineSpacing: 16, valign: "top", isTextBox: true, margin: 0,
  });

  s.addNotes("Point out the football row. The outdated fact scored 0.651, which is higher than most correct answers score. Similarity is confident and wrong.");
}

/* ================================================================== 10 */

{
  const s = contentSlide("Keeping the store from growing without limit", "Step 4, memory growth");

  const cards = [
    ["Facts are kept", "Extracted facts are small and already condensed, so they are never removed by trimming. They are the useful part of everything that was said.", GREEN],
    ["Raw messages are capped", "Once the store holds more than one hundred raw messages, the least useful are dropped first: least often retrieved, then oldest.", NAVY],
    ["Bigger is not better", "Every extra memory is another candidate competing for the same few slots in the results, so an oversized store retrieves less accurately, not more.", AMBER],
  ];

  let x = M;
  const cw = 3.86;
  cards.forEach(([title, text, accent]) => {
    card(s, x, 1.85, cw, 2.5, CARD);
    s.addShape(pres.ShapeType.ellipse, {
      x: x + 0.28, y: 2.12, w: 0.16, h: 0.16,
      fill: { color: accent }, line: { color: accent, width: 0 },
    });
    s.addText(title, {
      x: x + 0.56, y: 2.02, w: cw - 0.84, h: 0.38,
      fontFace: BODY, fontSize: 14.5, bold: true, color: accent,
      isTextBox: true, margin: 0,
    });
    s.addText(text, {
      x: x + 0.28, y: 2.5, w: cw - 0.56, h: 1.6,
      fontFace: BODY, fontSize: 12.5, color: INK,
      lineSpacing: 17, valign: "top", isTextBox: true, margin: 0,
    });
    x += cw + 0.24;
  });

  card(s, M, 4.62, 11.9, 1.85, ICE);
  s.addText("Replacing is not the same as deleting", {
    x: M + 0.34, y: 4.84, w: 11.2, h: 0.34,
    fontFace: BODY, fontSize: 14, bold: true, color: NAVY,
    isTextBox: true, margin: 0,
  });
  s.addText(
    "When a fact changes, the old version is marked as replaced and stays in the database so the " +
    "history can be read. When the user asks the assistant to forget a topic, those records are " +
    "removed from the database completely. The two are deliberately different operations, because " +
    "a request to delete personal data has to actually delete it.",
    {
      x: M + 0.34, y: 5.2, w: 11.2, h: 1.05,
      fontFace: BODY, fontSize: 13, color: INK,
      lineSpacing: 18, valign: "top", isTextBox: true, margin: 0,
    });

  s.addNotes("Trimming only touches raw messages. If asked what happens to a pruned message, the facts extracted from it were already saved separately, so the information is not lost.");
}

/* ================================================================== 11 */

{
  const s = contentSlide("Personal details are removed before saving", "Step 5, privacy");

  body(s,
    "Redaction happens on the way in, not on the way out. Email addresses, phone numbers and " +
    "identity numbers are replaced with a label before the record is written, so the real value " +
    "never reaches the database file at all.",
    { x: M, y: 1.62, w: 6.0, h: 1.25, fontSize: 14 });

  const points = [
    ["Nothing is sent away to be indexed", "The model that creates the vectors runs on this machine, so stored memories never travel to an API."],
    ["The user can ask for deletion", "A forget command removes every record about a topic from the database permanently."],
    ["An honest boundary", "Redaction protects what is stored. The message the user has just typed is still sent so the assistant can reply to it."],
  ];

  let py = 3.06;
  points.forEach(([h, t]) => {
    s.addShape(pres.ShapeType.ellipse, {
      x: M, y: py + 0.07, w: 0.14, h: 0.14,
      fill: { color: GREEN }, line: { color: GREEN, width: 0 },
    });
    s.addText(h, {
      x: M + 0.32, y: py, w: 5.7, h: 0.3,
      fontFace: BODY, fontSize: 13, bold: true, color: NAVY,
      isTextBox: true, margin: 0,
    });
    s.addText(t, {
      x: M + 0.32, y: py + 0.3, w: 5.7, h: 0.66,
      fontFace: BODY, fontSize: 12, color: MUTED,
      lineSpacing: 16, valign: "top", isTextBox: true, margin: 0,
    });
    py += 1.1;
  });

  s.addImage({
    path: path.join(ASSETS, "04a_privacy_store.png"),
    x: 7.1, y: 1.72, w: 5.62, h: 4.64,
  });
  caption(s, "The stored records, with the email and phone number already replaced.", 7.1, 6.44, 5.62);

  s.addNotes("Be ready for the follow up about the live turn. The answer is that redaction is applied at the storage boundary and redacting the live message is listed in future scope.");
}

/* ================================================================== 12 */

{
  const s = contentSlide("Results", "Evaluation");

  body(s,
    "Twenty two questions, with the correct answer for each decided before any test was run. " +
    "Twelve are worded plainly and ten the way people actually talk. Accuracy is not reported, " +
    "because almost every stored memory is irrelevant to any one question, so a system that " +
    "returned nothing at all would still score well on it.",
    { x: M, y: 1.58, w: 11.9, h: 0.86, fontSize: 13.5 });

  const rows = [
    ["Recall at 4",       "1.000",          "Every question found its memory"],
    ["MRR",               "1.000",          "The correct memory was always first"],
    ["Correct at rank 1", "22 of 22",       "No question was answered from the wrong memory"],
    ["Contradictions",    "4 of 4",         "New value returned, old value never"],
    ["Conversational",    "0.900 to 1.000", "After padding is stripped from the question"],
    ["Precision at 4",    "0.694",          "Capped by design, see the note below"],
  ];

  const cx = [M + 0.26, M + 3.5, M + 5.7];
  const cw = [3.1, 2.1, 5.9];

  s.addShape(pres.ShapeType.roundRect, {
    x: M, y: 2.50, w: 11.9, h: 0.44, rectRadius: 0.07,
    fill: { color: NAVY }, line: { color: NAVY, width: 0 },
  });
  ["MEASURE", "RESULT", "WHAT IT MEANS"].forEach((h, i) => {
    s.addText(h, {
      x: cx[i], y: 2.50, w: cw[i], h: 0.44,
      fontFace: BODY, fontSize: 10.5, bold: true, color: WHITE,
      charSpacing: 0.7, valign: "middle", isTextBox: true, margin: 0,
    });
  });

  let ry = 3.00;
  rows.forEach(([name, value, meaning], i) => {
    s.addShape(pres.ShapeType.roundRect, {
      x: M, y: ry, w: 11.9, h: 0.50, rectRadius: 0.06,
      fill: { color: i % 2 ? WHITE : CARD },
      line: { color: LINE, width: 0.75 },
    });
    s.addText(name, {
      x: cx[0], y: ry, w: cw[0], h: 0.50,
      fontFace: BODY, fontSize: 12.5, color: INK,
      valign: "middle", isTextBox: true, margin: 0,
    });
    s.addText(value, {
      x: cx[1], y: ry, w: cw[1], h: 0.50,
      fontFace: MONO, fontSize: 12.5, bold: true,
      color: i === 5 ? NAVY : GREEN,
      valign: "middle", isTextBox: true, margin: 0,
    });
    s.addText(meaning, {
      x: cx[2], y: ry, w: cw[2], h: 0.50,
      fontFace: BODY, fontSize: 12, color: MUTED,
      valign: "middle", isTextBox: true, margin: 0,
    });
    ry += 0.56;
  });

  card(s, M, 6.44, 11.9, 0.60, ICE);
  s.addText(
    "Each question has one correct memory and we return four, which caps precision at 0.25 by " +
    "definition. Rank one accuracy and MRR are the measures that fit this task.",
    {
      x: M + 0.32, y: 6.58, w: 11.3, h: 0.42,
      fontFace: BODY, fontSize: 12, color: INK,
      valign: "top", isTextBox: true, margin: 0,
    });

  s.addNotes("Read one row, not all six. Say that precision is capped by design before anyone asks why it is the lowest number here.");
}

/* ================================================================== 13 */

{
  const s = contentSlide("What this system does not do well", "Limitations");

  const limits = [
    ["Wording changes the score",
     "The same question phrased politely scores lower, because the extra words dilute the sentence vector. Stripping the padding recovers most of it, but the underlying weakness remains."],
    ["Extraction depends on consistent naming",
     "If the model records a detail as location one time and city the next, the two are never compared and a contradiction goes unnoticed."],
    ["Redaction covers storage only",
     "The message the user has just typed is still sent to the model, because the assistant has to read it in order to reply."],
    ["One user at a time",
     "There is a single memory store. Separating memory per user is designed for but not yet built."],
    ["A small test set",
     "Twenty two questions is enough to find real faults but too few to claim a precise figure. The numbers show behaviour, not a benchmark."],
  ];

  let ly = 1.78;
  limits.forEach(([h, t], i) => {
    const left = i < 3;
    const x = left ? M : M + 6.1;
    const y = left ? 1.78 + i * 1.55 : 1.78 + (i - 3) * 1.55;

    card(s, x, y, 5.8, 1.36, CARD);
    s.addText(h, {
      x: x + 0.28, y: y + 0.18, w: 5.24, h: 0.32,
      fontFace: BODY, fontSize: 13.5, bold: true, color: AMBER,
      isTextBox: true, margin: 0,
    });
    s.addText(t, {
      x: x + 0.28, y: y + 0.52, w: 5.24, h: 0.72,
      fontFace: BODY, fontSize: 11.5, color: MUTED,
      lineSpacing: 15, valign: "top", isTextBox: true, margin: 0,
    });
  });

  s.addNotes("Stating limitations plainly is worth marks. Do not hide the failure cases.");
}

/* ================================================================== 14 */

{
  const s = contentSlide("What this project is built on", "Foundations");

  const map = [
    ["Fixed context window of a transformer",
     "The reason the project exists. The model keeps no state between calls, so memory has to be built around it."],
    ["Text embeddings and vector space",
     "A local model turns each memory into 384 numbers so that meaning can be compared instead of words."],
    ["Cosine similarity search",
     "Retrieval ranks memories by the angle between vectors. Values are normalised, so the comparison is a dot product."],
    ["Retrieval augmented generation",
     "Retrieved memories are placed in the prompt before the model generates. The corpus searched is the user's own history."],
    ["Prompt design and system messages",
     "Memories go in the system message, kept separate from what the user actually said, so the two are never confused."],
    ["Decoding controls",
     "Temperature is zero when extracting facts so the result is repeatable, and higher when writing a reply."],
  ];

  s.addShape(pres.ShapeType.roundRect, {
    x: M, y: 1.66, w: 11.9, h: 0.46, rectRadius: 0.07,
    fill: { color: NAVY }, line: { color: NAVY, width: 0 },
  });
  s.addText("CONCEPT", {
    x: M + 0.24, y: 1.66, w: 4.2, h: 0.46,
    fontFace: BODY, fontSize: 10.5, bold: true, color: WHITE,
    charSpacing: 0.7, valign: "middle", isTextBox: true, margin: 0,
  });
  s.addText("WHERE IT IS USED", {
    x: M + 4.7, y: 1.66, w: 7.0, h: 0.46,
    fontFace: BODY, fontSize: 10.5, bold: true, color: WHITE,
    charSpacing: 0.7, valign: "middle", isTextBox: true, margin: 0,
  });

  let my = 2.2;
  map.forEach(([concept, use], i) => {
    s.addShape(pres.ShapeType.roundRect, {
      x: M, y: my, w: 11.9, h: 0.72, rectRadius: 0.06,
      fill: { color: i % 2 ? WHITE : CARD },
      line: { color: LINE, width: 0.75 },
    });
    s.addText(concept, {
      x: M + 0.24, y: my, w: 4.3, h: 0.72,
      fontFace: BODY, fontSize: 12.5, bold: true, color: NAVY,
      valign: "middle", isTextBox: true, margin: 0,
    });
    s.addText(use, {
      x: M + 4.7, y: my, w: 6.9, h: 0.72,
      fontFace: BODY, fontSize: 11.5, color: INK,
      valign: "middle", lineSpacing: 15, isTextBox: true, margin: 0,
    });
    my += 0.78;
  });

  s.addText("All six come from Unit 2, Transformers and Large Language Models.", {
    x: M, y: 6.92, w: 11.9, h: 0.32,
    fontFace: BODY, fontSize: 11, italic: true, color: FAINT,
    isTextBox: true, margin: 0,
  });

  s.addNotes("Be ready to be questioned on any row here.");
}

pres.writeFile({ fileName: OUT })
  .then(() => console.log("Written:", OUT))
  .catch((e) => { console.error(e); process.exit(1); });
